version: "3"
services:
  backend:
    image: backend:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9999:80

  frontend:
    image: frontend:1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile