version: "3"
services:
  backend:
    image: backend:1.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9999:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 1s
      timeout: 3s
      retries: 5

  frontend:
    image: frontend:1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8888:80
    depends_on:
      backend:
        condition: service_healthy